# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62994d1c14d516a20a7ee005a1ba56e975625ceab8d06c1895cac72b48973e0f7f6f13ade043084f5534d9cd50848dab263d5cab2b3322c86650d6c7c4d97311

test:
  secret_key_base: 1e784610df743447aceac82e72ee49f299cdde0b1852a20e14e6050fbc21c75b56357cf15d8ca059554e31bd7c410d9e4fe9728fe3e8af2019efb5584cf35630

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
